// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/users": {
            "get": {
                "description": "Get details of all users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get all users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.ResponseUser"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.ResponseUser": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "phone": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/entity.Role"
                },
                "status": {
                    "$ref": "#/definitions/entity.Status"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "entity.Role": {
            "type": "string",
            "enum": [
                "admin",
                "manager",
                "user"
            ],
            "x-enum-varnames": [
                "AdminRole",
                "ManagerRole",
                "UserRole"
            ]
        },
        "entity.Status": {
            "type": "string",
            "enum": [
                "active",
                "inactive",
                "pending",
                "deleted"
            ],
            "x-enum-varnames": [
                "Active",
                "Inactive",
                "Pending",
                "Deleted"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3021",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Golang Starter API",
	Description:      "This is a starter API for Golang projects",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
